id: image_generation
name: Image Generation
name[zh]: 图像生成
version: 1.0.0
icon: assets/icon.json
author: Sipeed Ltd
desc: Text-to-Image / Image-to-Image Large Models
desc[zh]: 文生图/图生图大模型
exclude:
  - dist
  - build
  - .gitignore
files:
  - assets/exit.jpg
  - assets/icon.json
  - app.yaml
  - main.py
  - README.md
