id: usb_pose_mario
name: USB Pose Mario
name[zh]: 姿态控制键盘
version: 1.0.0
author: Neucrack@Sipeed
icon: icon.json
desc: body moving as USB keyboard input to control game Super Mario
files:
  - main.py
  - icon.json
