id: local_vlm
name: Local VLM
name[zh]: 本地视觉大模型
version: 1.0.3
icon: assets/icon.png
author: Sipeed Ltd
desc: Local AI Vision Language Model
desc[zh]: 本地 AI 视觉大模型
exclude:
  - dist
  - build
  - .gitignore
include:
  - assets
  - app.yaml
  - main.py
  - README.md
