id: rtsp_stream
name: RTSP Stream
name[zh]: RTSP 推流
version: 1.0.1
icon: assets/app.png
author: Sipeed Ltd
desc: RTSP stream
desc[zh]: RTSP 推流
include:
  app.yaml: app.yaml
  assets: assets
  README.md: README.md
