id: thermal_camera
name: Thermal Camera
name[zh]: 热成像仪
version: 1.0.0
icon: assets/thermal.json
author: Sipeed Ltd
desc: Thermal Camera
desc[zh]: 热成像仪
files:
  - assets/thermal.json
  - app.yaml
  - main.py
