id: thermal256_night_vision
name: Thermal Night Vision
name[zh]: 热融合夜视仪
version: 1.0.0
icon: assets/thermal.json
author: Sipeed Ltd
desc: Thermal256 Night Vision
desc[zh]: 热融合夜视仪
files:
  - assets/thermal.json
  - app.yaml
  - main.py
