id: usb_hand_ctrl
name: USB Hand Contrl
name[zh]: 手势控制鼠标
version: 1.0.0
author: Neucrack@Sipeed
icon: icon.json
desc: detect hand status and simulate touchpad input through USB
files:
  - main.py
  - icon.json
