id: desktop_monitor
name: Desktop Monitor
name[zh]: 桌面监视器
version: 1.0.3
icon: assets/desktop_monitor.json
author: neucrack@Sipeed Ltd
desc: Monitoring PC info, or other info from internet or local.
desc[zh]: 监控电脑性能参数，或者其它来自互联网或者本地的数据。
exclude:
  - data
  - dist
  - .gitignore

