#include "ms_asr_tbl.h"

uint32_t lm_tbl_cnt = 0;
char** am_vocab = NULL;
char* lm_tbl[MAX_VOCAB_CNT];
uint16_t am2lm[MAX_VOCAB_CNT];

const char digit_char[16] = {
	'0','1','2','3','4','5','6','7','8','9','S','B','Q','W','.','_'
};

//无声调拼音，与声学模型绑定，10个每行
const char* am_pny_vocab[408]={\
"lv",    "shi",   "yang",  "chun",  "yan",   "jing",  "da",    "kuai",  "wen",   "zhang", 
"de",    "di",    "se",    "si",    "yue",   "lin",   "luan",  "geng",  "xian",  "huo",   
"xiu",   "mei",   "yi",    "ang",   "ran",   "ta",    "jin",   "ping",  "yao",   "bu",    
"li",    "liang", "zai",   "yong",  "dao",   "shang", "xia",   "fan",   "teng",  "dong",  
"she",   "xing",  "zhuang","ru",    "hai",   "tun",   "zhi",   "tou",   "you",   "ling",  
"pao",   "hao",   "le",    "zha",   "zen",   "me",    "zheng", "cai",   "ya",    "shu",   
"tuo",   "qu",    "fu",    "guang", "bang",  "zi",    "chong", "shui",  "cuan",  "ke",    
"shei",  "wan",   "hou",   "zhao",  "jian",  "zuo",   "cu",    "hei",   "yu",    "ce",    
"ming",  "dui",   "cheng", "men",   "wo",    "bei",   "dai",   "zhe",   "hu",    "jiao",  
"pang",  "ji",    "lao",   "nong",  "kang",  "yuan",  "chao",  "hui",   "xiang", "bing",  
"qi",    "chang", "nian",  "jia",   "tu",    "bi",    "pin",   "xi",    "zou",   "chu",   
"cun",   "wang",  "na",    "ge",    "an",    "ning",  "tian",  "xiao",  "zhong", "shen",  
"nan",   "er",    "ri",    "zhu",   "xin",   "wai",   "luo",   "gang",  "qing",  "xun",   
"te",    "cong",  "gan",   "lai",   "he",    "dan",   "wei",   "die",   "kai",   "ci",    
"gu",    "neng",  "ba",    "bao",   "xue",   "shuai", "dou",   "cao",   "mao",   "bo",    
"zhou",  "lie",   "qie",   "ju",    "chuan", "guo",   "lan",   "ni",    "tang",  "ban",   
"su",    "quan",  "huan",  "ying",  "a",     "min",   "meng",  "wu",    "tai",   "hua",   
"xie",   "pai",   "huang", "gua",   "jiang", "pian",  "ma",    "jie",   "wa",    "san",   
"ka",    "zong",  "nv",    "gao",   "ye",    "biao",  "bie",   "zui",   "ren",   "jun",   
"duo",   "ze",    "tan",   "mu",    "gui",   "qiu",   "bai",   "sang",  "jiu",   "yin",   
"huai",  "rang",  "zan",   "shuo",  "sha",   "ben",   "yun",   "la",    "cuo",   "hang",  
"ha",    "tuan",  "gong",  "shan",  "ai",    "kou",   "zhen",  "qiong", "ding",  "dang",  
"que",   "weng",  "qian",  "feng",  "jue",   "zhuan", "ceng",  "zu",    "bian",  "nei",   
"sheng", "chan",  "zao",   "fang",  "qin",   "e",     "lian",  "fa",    "lu",    "sun",   
"xu",    "deng",  "guan",  "shou",  "mo",    "zhan",  "po",    "pi",    "gun",   "shuang",
"qiang", "kao",   "hong",  "kan",   "dian",  "kong",  "pei",   "tong",  "ting",  "zang",  
"kuang", "reng",  "ti",    "pan",   "heng",  "chi",   "lun",   "kun",   "han",   "lei",   
"zuan",  "man",   "sen",   "duan",  "leng",  "sui",   "gai",   "ga",    "fou",   "kuo",   
"ou",    "suo",   "sou",   "nu",    "du",    "mian",  "chou",  "hen",   "kua",   "shao",  
"rou",   "xuan",  "can",   "sai",   "dun",   "niao",  "chui",  "chen",  "hun",   "peng",  
"fen",   "cang",  "gen",   "shua",  "chuo",  "shun",  "cha",   "gou",   "mai",   "liu",   
"diao",  "tao",   "niu",   "mi",    "chai",  "long",  "guai",  "xiong", "mou",   "rong",  
"ku",    "song",  "che",   "sao",   "piao",  "pu",    "tui",   "lang",  "chuang","keng",  
"liao",  "miao",  "zhui",  "nai",   "lou",   "bin",   "juan",  "zhua",  "run",   "zeng",  
"ao",    "re",    "pa",    "qun",   "lia",   "cou",   "tie",   "zhai",  "kuan",  "kui",   
"cui",   "mie",   "fei",   "tiao",  "nuo",   "gei",   "ca",    "zhun",  "nie",   "mang",  
"zhuo",  "pen",   "zun",   "niang", "suan",  "nao",   "ruan",  "qiao",  "fo",    "rui",   
"rao",   "ruo",   "zei",   "en",    "za",    "diu",   "nve",   "sa",    "nin",   "shai",  
"nen",   "ken",   "chuai", "shuan", "beng",  "ne",    "lve",   "qia",   "jiong", "pie",   
"seng",  "nuan",  "nang",  "miu",   "pou",   "cen",   "dia",   "o",     "zhuai", "yo",    
"dei",   "n",     "ei",    "nou",   "bia",   "eng",   "den",   "_",     };

//含声调拼音，与声学模型绑定，10个每行
//const char* am_tone_vocab[]={
const char* am_pnytone_vocab[1250]={\
"de",     "wo3",    "shi4",   "ni3",    "me",     "le",     "bu4",    "you3",   "yi1",    "tian1",  
"zai4",   "shi2",   "ge4",    "dao4",   "hao3",   "shen2",  "ma",     "lai2",   "ge1",    "yao4",   
"shang4", "gei3",   "xia4",   "ren2",   "hua4",   "dian4",  "shou3",  "mei2",   "zen3",   "yi4",    
"he2",    "ming2",  "li3",    "shuo1",  "zhe4",   "jiu4",   "zhi1",   "qu4",    "dian3",  "yi3",    
"fang4",  "xin1",   "xiang3", "jin1",   "jia1",   "hai2",   "hui4",   "zhong1", "a",      "da4",    
"wei4",   "yi2",    "xian4",  "ji1",    "di4",    "na4",    "hou4",   "duo1",   "neng2",  "bu2",    
"wu3",    "bo1",    "kan4",   "gong1",  "qi4",    "da3",    "ting1",  "ke3",    "sheng1", "ji3",    
"zuo4",   "xi1",    "yue4",   "jiao4",  "ji2",    "cheng2", "qing3",  "ba",     "er4",    "zui4",   
"ji4",    "kai1",   "yu3",    "dou1",   "ta1",    "jian4",  "xiao3",  "yang4",  "san1",   "zi4",    
"guo4",   "men",    "er2",    "fa1",    "hui2",   "chu1",   "zi",     "chi1",   "jing1",  "ye3",    
"nian2",  "nan2",   "xue2",   "ri4",    "na3",    "jiu3",   "yuan2",  "qi3",    "guo2",   "li4",    
"zhi4",   "yong4",  "jie2",   "qi1",    "yin1",   "zhou1",  "ai4",    "jin4",   "ne",     "che1",   
"lao3",   "ye4",    "qu3",    "qian2",  "xin4",   "fu4",    "dui4",   "si1",    "hao4",   "ban4",   
"ling2",  "xing2",  "wen4",   "kuai4",  "nv3",    "xiao4",  "shao3",  "ba1",    "qing2",  "bei4",   
"fang1",  "yu2",    "mei3",   "wan2",   "wan3",   "si4",    "ti2",    "zhu4",   "fu2",    "wang3",  
"zheng4", "jian1",  "zhao3",  "ru2",    "guan1",  "an1",    "zhi3",   "lu4",    "fen1",   "hen3",   
"bang1",  "liu4",   "you2",   "chang4", "dai4",   "ju4",    "yu4",    "zao3",   "zhen1",  "ping2",  
"du4",    "xi3",    "dong4",  "gao1",   "wen2",   "fan4",   "wu4",    "dong1",  "ban1",   "jie4",   
"ying1",  "liu2",   "cai2",   "xiang4", "shui4",  "gan3",   "xie1",   "tai4",   "cha2",   "de2",    
"dan4",   "ma3",    "suo3",   "yang2",  "jiang1", "yuan4",  "shi1",   "su4",    "shei2",  "qi2",    
"shen1",  "bao3",   "mian4",  "bie2",   "ding4",  "she4",   "qu1",    "zhang1", "xi4",    "wei2",   
"jue2",   "bai3",   "xiang1", "ya",     "qing1",  "zhi2",   "feng1",  "xie4",   "bao4",   "ke4",    
"zhan4",  "ben3",   "wu2",    "bi3",    "jia4",   "lian2",  "tong1",  "huan1",  "shu4",   "you4",   
"quan2",  "ba3",    "bei3",   "shi3",   "xing4",  "deng3",  "nei3",   "hai3",   "yan3",   "jie1",   
"guo3",   "bian4",  "le4",    "chang3", "gang1",  "tong2",  "zhu3",   "mu4",    "xing1",  "shu1",   
"hang2",  "jiao1",  "qiu2",   "chang2", "shang1", "shan1",  "jun1",   "yan2",   "fa3",    "huo3",   
"fei1",   "shui3",  "ti3",    "zhang3", "gen1",   "peng2",  "jiang3", "liang4", "piao4",  "jie3",   
"huang2", "liang3", "ying3",  "liao2",  "mai3",   "mo4",    "gan4",   "rang4",  "zhe",    "fei4",   
"wang2",  "lin2",   "cong2",  "ren4",   "ci4",    "gao4",   "shou1",  "zhao4",  "tou2",   "huo4",   
"zou3",   "ma1",    "wen1",   "xiao1",  "wai4",   "wang4",  "gai1",   "ci2",    "shou4",  "yong3",  
"fang2",  "ha1",    "guan3",  "duan3",  "nei4",   "kao3",   "dan1",   "men2",   "zhuan1", "zhe3",   
"jing4",  "da2",    "ran2",   "bi4",    "bian1",  "tai2",   "he1",    "hong2",  "zhun3",  "xing3",  
"guang3", "zi1",    "hua2",   "diao4",  "hua1",   "zhong4", "yun4",   "zhong3", "gu3",    "ka3",    
"chen2",  "la",     "xian1",  "xu1",    "leng3",  "xiu1",   "chuan1", "yao1",   "bai2",   "se4",    
"hu2",    "ge2",    "jian3",  "qian1",  "po2",    "tu2",    "rong2",  "qin1",   "huo2",   "huan4",  
"gu4",    "ke1",    "te4",    "yin2",   "dang1",  "zhen4",  "chuang2","pian4",  "xun2",   "pai2",   
"bing4",  "chan3",  "wan4",   "xi2",    "lei4",   "kou3",   "si3",    "pin3",   "dao3",   "chuan2", 
"gou4",   "hu4",    "biao3",  "mo2",    "song4",  "li2",    "lv4",    "sheng4", "suan4",  "guang1", 
"ba4",    "tiao2",  "kong1",  "min2",   "zhuang1","pian1",  "o2",     "shao4",  "du2",    "yuan3",  
"er3",    "hei1",   "han2",   "ying2",  "nao3",   "zong3",  "zhu1",   "long2",  "lian4",  "wei3",   
"zuo2",   "an4",    "wei1",   "ban3",   "chi2",   "fen4",   "lan2",   "sha1",   "mai4",   "yan4",   
"xu3",    "luo4",   "ru4",    "re4",    "cuo4",   "jin3",   "sheng3", "man4",   "pei2",   "sha2",   
"can1",   "fou3",   "sai4",   "chu3",   "ze2",    "han4",   "yun2",   "sou1",   "chun1",  "xue3",   
"liang2", "fan1",   "cai3",   "tang2",  "ting2",  "xiong1", "duan4",  "jing3",  "ying4",  "shu3",   
"zhuan3", "yue1",   "mi4",    "xu4",    "kuang4", "xun4",   "que4",   "mang2",  "xie3",   "qin2",   
"huai2",  "zhao1",  "pu3",    "ce4",    "sui4",   "fan2",   "ning2",  "gui4",   "qun2",   "dong3",  
"bao1",   "gai3",   "geng4",  "gui1",   "chao1",  "hun1",   "di1",    "liao3",  "dou4",   "chu2",   
"mei4",   "pin2",   "lou2",   "qiang2", "mi3",    "you1",   "tui1",   "chong1", "mao4",   "xian3",  
"fan3",   "cai4",   "bing1",  "gai4",   "du1",    "la1",    "ju2",    "jia3",   "xiong2", "meng4",  
"nin2",   "zheng1", "di3",    "su1",    "biao1",  "lun2",   "bo2",    "gu1",    "kuan3",  "ya4",    
"jiao3",  "chong2", "mao2",   "xuan3",  "er",     "n2",     "hui1",   "hu1",    "zu3",    "shuang1",
"na2",    "tong3",  "zu2",    "luo2",   "qing4",  "yang3",  "lie4",   "dang4",  "tuan2",  "cun1",   
"tan2",   "nong2",  "bin1",   "ci3",    "kong4",  "zheng3", "gong4",  "chu4",   "fu1",    "yin3",   
"zhan3",  "chao2",  "xuan1",  "tao2",   "pei4",   "huan2",  "zi3",    "ma2",    "jiang4", "tuo1",   
"ya1",    "wu1",    "tian2",  "lv3",    "ao4",    "teng2",  "ya2",    "ling3",  "zhang4", "cun2",   
"pi2",    "tie3",   "kang1",  "gang3",  "gao3",   "fu3",    "ruan3",  "ceng2",  "cheng1", "a1",     
"ting3",  "sui2",   "pa4",    "xian2",  "deng1",  "shun4",  "xie2",   "liao4",  "mu3",    "e2",     
"qiao2",  "bai4",   "cha4",   "hai4",   "di2",    "ku4",    "yao2",   "man3",   "zao4",   "gan1",   
"niu2",   "xiang2", "za3",    "weng1",  "bei1",   "song1",  "e4",     "ben4",   "wa2",    "qie4",   
"xia2",   "nian4",  "qiu1",   "ming4",  "nao4",   "zeng1",  "mian3",  "pao3",   "huai4",  "rou4",   
"zhuang4","yan1",   "tu3",    "tao4",   "fei2",   "zhe2",   "guan4",  "shao1",  "meng2",  "ju1",    
"ai1",    "lian3",  "nai3",   "ling4",  "lang2",  "qie3",   "sha3",   "zuo3",   "guo1",   "ya3",    
"pai1",   "quan1",  "ken3",   "chang1", "chuang4","tu1",    "wan1",   "yang1",  "sun1",   "tui4",   
"bu3",    "lun4",   "ye2",    "xiu4",   "shuai4", "yun3",   "zan2",   "po4",    "tong4",  "zong1",  
"xue4",   "nong4",  "ku3",    "yong1",  "gou3",   "heng2",  "feng4",  "lang4",  "mian2",  "ni2",    
"gui3",   "xu2",    "jiu1",   "mou3",   "wen3",   "pan2",   "shen3",  "tiao4",  "kuo4",   "ju3",    
"gun3",   "shan4",  "gua1",   "cha1",   "cao3",   "shang3", "ruo4",   "bi1",    "qian4",  "min3",   
"pi1",    "kai3",   "nuan3",  "cong1",  "yin4",   "guai1",  "du3",    "guai4",  "chao3",  "pai4",   
"que1",   "mi2",    "bei",    "kao4",   "qiong2", "ku1",    "ou1",    "zhao2",  "jun4",   "niang2", 
"tan4",   "lan3",   "pao4",   "xuan2",  "fa4",    "hu3",    "kun1",   "?",      "gua4",   "kong3",  
"nuo4",   "zou4",   "lia3",   "tao3",   "kou4",   "lei2",   "bang3",  "geng1",  "rui4",   "zhuo2",  
"zha1",   "ding1",  "juan1",  "lao2",   "lu2",    "pang2",  "rao3",   "luan4",  "cang1",  "za2",    
"tie1",   "lu3",    "zu1",    "fen3",   "miao2",  "pan4",   "ding3",  "shua1",  "niao3",  "rou2",   
"he4",    "cang2",  "zhui1",  "chun2",  "duan1",  "zhuan4", "tou",    "dun4",   "la4",    "da1",    
"quan4",  "kun4",   "fang3",  "cao1",   "en1",    "cai1",   "chui1",  "chou2",  "zan4",   "wo4",    
"suan1",  "shua3",  "zai3",   "gun4",   "bang4",  "dang3",  "tou4",   "shu2",   "kuang2", "chuang1",
"pi4",    "qiang1", "shuang3","run4",   "pian2",  "sui1",   "mao1",   "hao2",   "chi4",   "zhu2",   
"lei3",   "tao1",   "pang4",  "sun3",   "zhou4",  "zun1",   "cui1",   "dao1",   "duo3",   "kuan1",  
"ran3",   "die2",   "tang4",  "xuan4",  "zhuo1",  "fa2",    "zui3",   "san3",   "shan3",  "ti4",    
"san4",   "nu3",    "yuan1",  "zhai4",  "gou1",   "zang4",  "pan1",   "piao1",  "hou2",   "miao4",  
"qiang3", "deng4",  "lve4",   "sa4",    "wo1",    "zhua1",  "ma4",    "mo1",    "ta3",    "die1",   
"hun2",   "ou3",    "tui3",   "chou1",  "chi3",   "po1",    "pu2",    "sen1",   "miao3",  "kang4",  
"reng2",  "yun1",   "tan1",   "shen4",  "tang1",  "guang4", "bing3",  "tan3",   "ru3",    "pu4",    
"juan3",  "zhai2",  "nai4",   "bi2",    "sao3",   "shai4",  "dun1",   "o1",     "han3",   "wang1",  
"cu4",    "zao1",   "can2",   "tou1",   "pin4",   "ni4",    "liu3",   "qiao3",  "ka1",    "hun4",   
"diu1",   "hui3",   "men4",   "xia1",   "man2",   "fo2",    "tang3",  "tu4",    "shuai1", "re3",    
"juan4",  "tai1",   "kua4",   "ren3",   "chai1",  "mie4",   "yo1",    "suo1",   "che4",   "zha4",   
"sai1",   "chou3",  "cao2",   "cui4",   "dai1",   "hai1",   "wa1",    "pa2",    "feng2",  "duo2",   
"huo",    "sang1",  "su2",    "she3",   "luo3",   "lang3",  "xue1",   "sha4",   "lai4",   "she2",   
"shao2",  "zhen3",  "huan3",  "ni1",    "kan1",   "peng4",  "lan4",   "chou4",  "niu1",   "xun1",   
"sa1",    "shi",    "ti1",    "zai1",   "wa",     "niu3",   "ca1",    "hen4",   "chan2",  "qin3",   
"heng1",  "niao4",  "shuai3", "ben1",   "wa3",    "che3",   "lei",    "diao1",  "an3",    "qiao1",  
"kui1",   "wai1",   "kan3",   "pin1",   "meng3",  "lei1",   "shuo4",  "chong3", "zhan1",  "tun2",   
"ba2",    "ao2",    "wa4",    "chai2",  "lou4",   "qiao4",  "nu4",    "yao3",   "rao4",   "dian1",  
"guai3",  "keng1",  "huang1", "dan3",   "kui2",   "ta4",    "sao1",   "liu1",   "bao2",   "kui4",   
"mi1",    "ke2",    "huang3", "chuang3","zuan1",  "cun4",   "kua1",   "dui1",   "geng3",  "qu2",    
"mou2",   "zhai1",  "zeng4",  "zong4",  "bo",     "jiong3", "qia4",   "chuan4", "pu1",    "tiao1",  
"zhui4",  "lv2",    "ga1",    "cu1",    "tuo2",   "pi3",    "tiao3",  "ang2",   "qian3",  "fei3",   
"ning4",  "ei2",    "can4",   "chen4",  "long3",  "chui2",  "can3",   "zei2",   "quan3",  "rao2",   
"mai2",   "pao1",   "fen2",   "ai2",    "pen1",   "zang1",  "chun3",  "nan4",   "qie1",   "dou3",   
"zha2",   "piao2",  "pen2",   "hen2",   "cou4",   "ye1",    "beng4",  "gua3",   "hong3",  "sa3",    
"nang2",  "bian3",  "mu2",    "nu2",    "tuo4",   "e3",     "sang3",  "po3",    "gong3",  "kuang1", 
"zhe1",   "ping1",  "han1",   "reng1",  "hong1",  "seng1",  "beng1",  "sou4",   "nie4",   "tun1",   
"chan4",  "sang4",  "pang1",  "li1",    "pa1",    "qie2",   "tuo3",   "lao1",   "ge3",    "li",     
"nen4",   "diao3",  "peng1",  "duo4",   "sheng2", "zhai3",  "zhou2",  "ai3",    "zuan4",  "lao4",   
"bie1",   "nve4",   "lang1",  "leng2",  "dai3",   "luan2",  "lu1",    "lie3",   "la3",    "lin4",   
"jia2",   "mo3",    "nie1",   "cheng4", "luan3",  "cuo1",   "zou1",   "rang3",  "mie1",   "nuo2",   
"men1",   "dei3",   "weng4",  "mao3",   "fu",     "hou3",   "peng3",  "chuo4",  "qin4",   "kun3",   
"kua3",   "shui2",  "pao2",   "ceng4",  "she1",   "shuan1", "song3",  "yu1",    "qia3",   "sui3",   
"shuan4", "tian3",  "suo",    "rui3",   "ao3",    "nian3",  "gu2",    "zan3",   "lou3",   "e1",     
"pei1",   "chen1",  "chuan3", "ga4",    "pou1",   "bin4",   "cuan4",  "niang4", "chuai1", "ga2",    
"di",     "ci1",    "zhua3",  "luo1",   "bai1",   "cheng3", "gang4",  "kang2",  "qia1",   "miao1",  
"xiu3",   "chuo1",  "zhou3",  "feng3",  "pie3",   "mang3",  "po",     "ao1",    "zhuai1", "pie1",   
"bo4",    "nang1",  "kou1",   "na1",    "long4",  "tui2",   "huang4", "leng4",  "cen2",   "xin2",   
"zha3",   "miu4",   "shang",  "bie4",   "bo3",    "nao2",   "nan3",   "hao1",   "wai3",   "qiu3",   
"lu",     "la2",    "hu",     "chong4", "ang1",   "cha3",   "beyond", "heng4",  "ha2",    "de1",    
"chuai4", "jue1",   "ne2",    "shai3",  "en4",    "n",      "cuo2",   "shai1",  "ceng1",  "za1",    
"nian1",  "zao2",   "zuo1",   "liao1",  "piao3",  "beng2",  "mo",     "du",     "jiao2",  "sao4",   
"cui3",   "huo1",   "sa",     "ne4",    "ze4",    "ju",     "que2",   "ha3",    "nan1",   "meng1",  
"le1",    "chan1",  "ang4",   "qi",     "lin1",   "zan1",   "cuan1",  "shun3",  "me1",    "jia",    
"tuan1",  "liang",  "hou",    "qie",    "sou3",   "bing",   "xiao2",  "qq",     "rui2",   "hong4",  
"rong1",  "zuan3",  "gen4",   "pin",    "sam",    "chuai3", "fang",   "sheng",  "lao",    "hang1",  
"lin3",   "lun1",   "zhuai3", "chen3",  "da",     "rang1",  "dun3",   "bu1",    "e",      "tun4",   
"tan",    "lie1",   "gen3",   "tie4",   "jie",    "qiong1", "he",     "ga3",    "man",    "qiang4", 
"rang2",  "cen1",   "kuai3",  "rong3",  "nou4",   "hao",    "cuan2",  "yong2",  "cu2",    "_",  
};
